USE demo;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  student_id VARCHAR(20) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
  ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'verified' AFTER password_hash,
  ADD COLUMN verification_token VARCHAR(255) NULL AFTER status,
  ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1 AFTER verification_token,
  ADD COLUMN is_admin TINYINT(1) NOT NULL DEFAULT 0 AFTER is_active,
  ADD COLUMN created_by VARCHAR(255) NULL AFTER created_at,
  ADD COLUMN data_hash VARCHAR(255) NULL AFTER created_by;


